language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
install:
  - "pip install tox"
  - "pip install coveralls"
script: "tox -- -rs"
after_success:
  - coveralls
